---
- hosts: webservers
  vars:
    - WelcomeMsg: "Welcome to this demo"

  tasks:
  - name: Setup Nginx
    yum: name=nginx sate=present enablerepo=nginx
  - name: Copy index.html file
    template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
